{
 "title": "Kafka",
 "description": "Dashboard for metrics jmx_exporter protmetheus",
 "tags": [ "kafka" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(kafka_controller_kafkacontroller_controllerstate, job)"
   },
   {
    "name": "broker",
    "label": "broker",
    "query": "label_values(kafka_controller_kafkacontroller_controllerstate{job=\"$job\"}, broker)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_cluster_partition_replicascount{job=\"$job\"}, topic)"
   },
   {
    "name": "online_broker",
    "query": "query_result(count(up{job=~\"$job\"}))"
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": "label_values(kafka_log_log_size{job=\"$job\",broker=~\"$broker\",topic=~\"$topic\"}, partition)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brokers Online",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Total of Topics",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_replicascount{job=~\"$job\",broker=~\"$broker\",topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Controller and Followers ",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Partitions Leader and Replica Per Broker",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_leadercount{job=~\"$job\"}"
    },
    {
     "expr": "count(kafka_cluster_partition_replicascount{job=\"$job\"} <= 1)by(broker)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(container_memory_usage_bytes{container_label_com_docker_compose_service=~\"$broker\"})",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Usage/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=~\"$broker\"}[5m])) by (container_label_com_docker_compose_service)",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{container_label_com_docker_compose_service=~\"$broker\"}",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  { "title": "Request Handler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Request Handler Avg Usage [$broker]",
   "type": "gauge",
   "description": "If <= 0 is very idle",
   "gridPos": { "x": 0, "y": 21, "w": 24, "h": 5 },
   "repeat": "broker",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - irate(kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent_count{job=\"$job\",broker=~\"$broker\"}[5m]) / 10000000",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Total Time Produce Latency 99th [$broker]",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 27, "w": 8, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems{request=\"Produce\",job=\"$job\",quantile=\"0.99\",broker=~\"$broker\"})by(request)",
     "legendFormat": "Total time"
    }
   ]
  },
  {
   "title": "Total Time FetchConsumer Latency 99th [$broker]",
   "type": "gauge",
   "gridPos": { "x": 8, "y": 27, "w": 8, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems{request=\"FetchConsumer\",job=\"$job\",quantile=\"0.99\",broker=~\"$broker\"})by(request)",
     "legendFormat": "Total time"
    }
   ]
  },
  {
   "title": "Total Time FetchFollower Latency 99th [$broker]",
   "type": "gauge",
   "gridPos": { "x": 16, "y": 27, "w": 8, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_totaltimems{request=\"FetchFollower\",job=\"$job\",quantile=\"0.99\",broker=~\"$broker\"})by(request)",
     "legendFormat": "Total time"
    }
   ]
  },
  {
   "title": "Produce Latency 99th per Broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg (kafka_network_requestmetrics_totaltimems{request=\"Produce\",job=\"$job\",quantile=\"0.99\",broker=~\"$broker\"})by(broker)",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "FetchConsumer Latency 99th per Broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg (kafka_network_requestmetrics_totaltimems{request=\"FetchConsumer\",job=\"$job\",quantile=\"0.99\",broker=~\"$broker\"})by(broker)",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "FetchFollow Latency 99th per Broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg (kafka_network_requestmetrics_totaltimems{request=\"FetchFollower\",job=\"$job\",quantile=\"0.99\",broker=~\"$broker\"})by(broker)",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "reqps", "label": "Message/s" }
   ],
   "targets": [
    {
     "expr": "sort(sum(irate(kafka_server_brokertopicmetrics_messagesin_total{job=\"$job\",broker=~\"$broker\",topic!=\"\",topic=~\"$topic\"}[5m]))by(topic))",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_brokertopicmetrics_bytesin_total{job=\"$job\",topic!=\"\",broker=~\"$broker\",topic=~\"$topic\"}[5m]))by(topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_brokertopicmetrics_bytesout_total{job=\"$job\",broker=~\"$broker\",topic!=\"\",topic=~\"$topic\"}[5m]))by(topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Total Produce Request Rate Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_brokertopicmetrics_totalproducerequests_total{job=\"$job\",broker=~\"$broker\",topic!=\"\",topic=~\"$topic\"}[5m]))by(topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Log Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_log_log_size{job=\"$job\",broker=~\"$broker\",topic=~\"$topic\",partition=~\"$partition\",topic!=\"__consumer_offsets\"}",
     "legendFormat": "{{topic}}:{{partition}}"
    }
   ]
  },
  {
   "title": "Produce Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_network_requestmetrics_requests_total{request=~\"Produce\",job=\"$job\",broker=~\"$broker\"}[5m]))by(broker)",
     "legendFormat": "Request: {{broker}}"
    }
   ]
  },
  {
   "title": "Bytes In / Out Per Broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "Bps", "label": "In (-) / Out (+)" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_brokertopicmetrics_bytesout_total{job=\"$job\",broker=~\"$broker\",topic!=\"\"}[5m]))by(broker)",
     "legendFormat": "Bytes Out [{{broker}}]"
    },
    {
     "expr": "sum (irate(kafka_server_brokertopicmetrics_bytesin_total{job=\"$job\",broker=~\"$broker\",topic!=\"\"}[5m]))by(broker)",
     "legendFormat": "Bytes In [{{broker}}]"
    }
   ]
  },
  { "title": "Troubleshooting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Failed Produce Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedproducerequests_total{job=~\"$job\",broker=~\"$broker\"}[1m]))by(broker)",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Failed Fetch Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedfetchrequests_total{job=~\"$job\",broker=~\"$broker\"}[1m]))by(broker)",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Failed Produce Request Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedproducerequests_total{job=~\"$job\",topic!=\"\",broker=~\"$broker\",topic=~\"$topic\"}[1m]))by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Failed Fetch Request Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedfetchrequests_total{job=~\"$job\",topic!=\"\",broker=~\"$broker\",topic=~\"$topic\"}[1m]))by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Disconnects Per Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "ms", "label": "Time/ms" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_sessionexpirelistener_zookeeperdisconnects_total{job=\"$job\",broker=~\"$broker\"}[1m]))by(broker)",
     "legendFormat": "Broker - {{broker}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Expires Per Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 113 },
   "yaxes": [
    { "format": "ms", "label": "Time/ms" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_sessionexpirelistener_zookeeperexpires_total{job=\"$job\",broker=~\"$broker\"}[1m]))by(broker)",
     "legendFormat": "Broker - {{broker}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Request Latency Ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 113 },
   "yaxes": [
    { "format": "ms", "label": "Time/ms" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms{job=\"$job\",broker=~\"$broker\"})by(broker)",
     "legendFormat": "Broker: {{broker}}"
    }
   ]
  },
  {
   "title": "Isr Shrinks / Isr Expands Per Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "ops", "label": "Expands (-) / Shrinks (+)" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_replicamanager_isrshrinks_total{job=\"$job\",broker=~\"$broker\"}[1m]))",
     "legendFormat": "ISR Shrinks Per Sec"
    },
    {
     "expr": "sum (irate(kafka_server_replicamanager_isrexpands_total{job=\"$job\",broker=~\"$broker\"}[1m]))",
     "legendFormat": "ISR Expands Per Sec"
    }
   ]
  },
  {
   "title": "FetchFollower Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 122 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_network_requestmetrics_requests_total{request=~\"FetchFollower\",job=\"$job\",broker=~\"$broker\"}[5m]))by(broker)",
     "legendFormat": "Request: {{broker}}"
    }
   ]
  },
  {
   "title": "FetchConsumer Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_network_requestmetrics_requests_total{request=\"FetchConsumer\",job=\"$job\",broker=~\"$broker\"}[5m]))by(broker)",
     "legendFormat": "Request: {{broker}}"
    }
   ]
  },
  {
   "title": "Number of Requests Waiting in the Fetch Purgatory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 131 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_delayedoperationpurgatory_purgatorysize{job=\"$job\",delayedOperation=\"Fetch\",broker=~\"$broker\"})by(broker)",
     "legendFormat": "Broker {{broker}}"
    }
   ]
  },
  {
   "title": "Total Fetch Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "reqps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{job=\"$job\",broker=~\"$broker\",topic!=\"\"}[1m]))by(broker)",
     "legendFormat": "Broker: {{broker}}"
    }
   ]
  },
  {
   "title": "Log Flush Stats Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 140 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_log_logflushstats_logflushrateandtimems_count{job=\"$job\",broker=~\"$broker\"}[5m]))by(broker)",
     "legendFormat": "Broker - {{broker}}"
    }
   ]
  },
  {
   "title": "Number of Requests Waiting in the Producer Purgatory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_delayedoperationpurgatory_purgatorysize{job=\"$job\",delayedOperation=\"Produce\",broker=~\"$broker\"})by(broker)",
     "legendFormat": "Broker {{broker}}"
    }
   ]
  },
  {
   "title": "Leader Election Rate Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 149 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_controller_controllerstats_leaderelectionrateandtimems_count{job=\"$job\",broker=~\"$broker\"}[1m]))by(broker)",
     "legendFormat": "Broker - {{broker}}"
    }
   ]
  },
  {
   "title": "Partitions Leader Per Broker",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 158 },
   "targets": [
    {
     "expr": "kafka_cluster_partition_replicascount{job=~\"$job\",topic=~\"$topic\"}"
    }
   ]
  },
  {
   "title": "Disk Usage Segment Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort(sum(kafka_log_log_size{job=~\"$job\",broker=~\"$broker\"}) by (broker))",
     "legendFormat": "broker Broker: {{broker}}"
    }
   ]
  },
  {
   "title": "Count Partition per Broker",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 172 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort(sum(kafka_server_replicamanager_partitioncount{job=~\"$job\"}) by (broker))",
     "legendFormat": "broker Broker: {{broker}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 177 } },
  {
   "title": "JVM Threads Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 178 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"$job\",broker=~\"$broker\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 178 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"$job\",broker=~\"$broker\"} )",
     "legendFormat": "Broker - {{broker}}"
    }
   ]
  },
  {
   "title": "GC CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 187 },
   "yaxes": [
    { "format": "short", "label": "Usage/s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\",broker=~\"$broker\"}[5m])",
     "legendFormat": "Broker - {{broker}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 187 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"$job\",broker=~\"$broker\"}[1m]))",
     "legendFormat": "{{broker}}"
    }
   ]
  }
 ]
}