global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: "standalone_monitor"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - "prometheus:9090"

  - job_name: "zookeeper"
    static_configs:
      - targets:
        - "zoo1:9999"
        - "zoo2:9999"
        - "zoo3:9999"

  - job_name: "kafka"
    static_configs:
      - targets:
        - "kafka1:9999"
        labels:
          broker: 'kafka1'
      - targets:
        - "kafka2:9999"
        labels:
          broker: 'kafka2'
      - targets:
        - "kafka3:9999"
        labels:
          broker: 'kafka3'

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080